### ISSUE TITLE
您好，可以给完整源代码吗？谢谢！

### ISSUE THREAD

**Issue by xiaozheer** [chenlong-clock/CFED-HANet#3]

**Comment by chenlong-clock** [comment]
Hello, the code about the HANet implementation is fully open source. Could you let me know which part you have a question?

**Comment by xiaozheer** [comment]
Hello, train.py uses the stream method for data partitioning. How should I modify it to use the train method instead? I want to achieve the results reported in the paper.

**Comment by chenlong-clock** [comment]
Thanks for reminding me of the stream, I found a bug caused by the version. You can ignore the 
` PERM_5 = [[0, 1, 2, 3, 4], [4, 3, 2, 1, 0], [0, 3, 1, 4, 2], [1, 2, 0, 3, 4], [3, 4, 0, 1, 2]] `
and
` PERM_10 = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]] `
and comment out the line: https://github.com/chenlong-clock/CFED-HANet/blob/2b11618d490c15ab307918b0f9510b6138aec3bf/train.py#L60
with `#   streams = [streams[l] for l in PERM[int(args.perm_id)]] # permute the stream
`.

By modifying the `--perm-id`, the code will automatically use the permutation: https://github.com/chenlong-clock/CFED-HANet/tree/2b11618d490c15ab307918b0f9510b6138aec3bf/data_incremental/MAVEN/perm1.

I will commit to a new version as soon as possible.

**Comment by xiaozheer** [comment]
If I want to run the experiments shown in Table 1 and Table 2 of your paper, how can I do that? 
Specifically, how do I use the data inside the perm0 folder?
data_incremental/MAVEN/perm0/MAVEN_5task_4way_5shot.train.jsonl
data_incremental/MAVEN/perm0/MAVEN_5task_4way_10shot.train.jsonl
Thank you!!!

**Comment by chenlong-clock** [comment]
The main results in Table 1 and Table 2 do not use different permutations. You can run the script [MAVEN_all_fwUCL+TCL.sh ](https://github.com/chenlong-clock/CFED-HANet/blob/ebf194160e62e4ccd1fce4e9f4c7bcbe4ab83ab9/MAVEN_all_fwUCL%2BTCL.sh) with the random seeds and the hyperparameters mentioned in https://github.com/chenlong-clock/CFED-HANet/blob/ebf194160e62e4ccd1fce4e9f4c7bcbe4ab83ab9/readme.md?plain=1#L25C1-L26C1

**Comment by xiaozheer** [comment]
I still don't quite understand, can we add a contact information? This is my WeChat: xt18827064675
Please！Thank you！！！
